# Generated by Django 5.2.4 on 2025-09-27 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_email_unique_index"),
        ("registration", "0003_profile_cargo_profile_telefono"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rol", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TipoIncidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_problema", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "tipo_gravedad",
                    models.CharField(
                        choices=[("A", "Alta"), ("M", "Media"), ("B", "Baja")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_direccion", models.CharField(max_length=100)),
                ("estado", models.BooleanField(default=True)),
                ("creadoEl", models.DateTimeField(auto_now_add=True)),
                ("actualizadoEl", models.DateTimeField(auto_now=True)),
                (
                    "encargado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direcciones_encargadas",
                        to="registration.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_departamento", models.CharField(max_length=100)),
                ("estado", models.BooleanField(default=True)),
                ("creadoEl", models.DateTimeField(auto_now_add=True)),
                ("actualizadoEl", models.DateTimeField(auto_now=True)),
                (
                    "encargado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departamentos_encargados",
                        to="registration.profile",
                    ),
                ),
                (
                    "direccion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.direccion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Encuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("ubicacion", models.CharField(max_length=200)),
                ("estado", models.BooleanField(default=True)),
                ("creadoEl", models.DateTimeField(auto_now_add=True)),
                ("actualizadoEl", models.DateTimeField(auto_now=True)),
                ("prioridad", models.CharField(max_length=50)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.departamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JefeCuadrilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cuadrilla", models.CharField(max_length=100)),
                (
                    "departamento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.departamento",
                    ),
                ),
                (
                    "encargado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuadrillas_encargadas",
                        to="registration.profile",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuadrillas",
                        to="registration.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("estado", models.CharField(max_length=50)),
                ("prioridad", models.CharField(max_length=50)),
                ("creadoEl", models.DateTimeField(auto_now_add=True)),
                ("actualizadoEl", models.DateTimeField(auto_now=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
                ("nombre_vecino", models.CharField(max_length=100)),
                ("correo_vecino", models.EmailField(max_length=254)),
                ("telefono_vecino", models.CharField(max_length=20)),
                (
                    "departamento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.departamento",
                    ),
                ),
                (
                    "encuesta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.encuesta",
                    ),
                ),
                (
                    "cuadrilla",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.jefecuadrilla",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Derivacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_derivacion", models.DateTimeField()),
                ("fecha_finalizacion", models.DateTimeField(blank=True, null=True)),
                (
                    "incidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.incidencia",
                    ),
                ),
                (
                    "jefe_cuadrilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.jefecuadrilla",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Multimedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("tipo", models.CharField(max_length=50)),
                ("formato", models.CharField(max_length=50)),
                ("creadoEl", models.DateTimeField(auto_now_add=True)),
                (
                    "incidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multimedias",
                        to="core.incidencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreguntaEncuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_pregunta", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("tipo", models.CharField(max_length=50)),
                (
                    "encuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.encuesta"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespuestaEncuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_respuesta", models.TextField()),
                ("tipo", models.CharField(max_length=50)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.preguntaencuesta",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="incidencia",
            name="respuesta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.respuestaencuesta",
            ),
        ),
        migrations.CreateModel(
            name="Territorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="territoriales",
                        to="core.incidencia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="incidencia",
            name="tipo_incidencia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.tipoincidencia",
            ),
        ),
    ]
