# Generated by Django 5.2.6 on 2025-11-04 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preguntaencuesta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("texto", "Texto"),
                    ("numero", "Número"),
                    ("opcion", "Opción múltiple"),
                ],
                default="texto",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PreguntaBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_pregunta", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("numero", "Número"),
                            ("opcion", "Opción múltiple"),
                        ],
                        default="texto",
                        max_length=50,
                    ),
                ),
                (
                    "tipo_incidencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas_base",
                        to="core.tipoincidencia",
                    ),
                ),
            ],
        ),
    ]
