# Generated by Django 5.2.4 on 2025-11-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_multimedia_options_remove_multimedia_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encuesta",
            name="prioridad",
            field=models.CharField(
                choices=[("Baja", "Baja"), ("Media", "Media"), ("Alta", "Alta")],
                max_length=50,
            ),
        ),
    ]
