# Generated by Django 5.2.6 on 2025-11-04 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_preguntaencuesta_tipo_preguntabase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respuestaencuesta",
            name="pregunta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas",
                to="core.preguntaencuesta",
            ),
        ),
    ]
