# Generated by Django 5.2.4 on 2025-10-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_direccion_encargado"),
        ("registration", "0003_profile_cargo_profile_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="direccion",
            name="encargado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direcciones_encargadas",
                to="registration.profile",
            ),
        ),
    ]
