# Generated by Django 5.2.6 on 2025-10-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_direccion_encargado"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidencia",
            name="motivo_rechazo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
