# Generated by Django 5.2.4 on 2025-11-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_incidencia_motivo_rechazo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidencia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("En Progreso", "En Progreso"),
                    ("Completada", "Completada"),
                    ("Rechazada", "Rechazada"),
                ],
                default="Pendiente",
                max_length=50,
            ),
        ),
    ]
