# Generated by Django 5.2.4 on 2025-11-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_incidencia_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidencia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "pendiente"),
                    ("En Progreso", "en Progreso"),
                    ("Completada", "completada"),
                    ("Rechazada", "rechazada"),
                    ("Validada", "validada"),
                ],
                default="Pendiente",
                max_length=50,
            ),
        ),
    ]
