# Generated by Django 5.2.4 on 2025-10-14 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='incidencias/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('es_resolucion', models.BooleanField(default=False, help_text='Indica si esta imagen es de la resolución de la incidencia')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.incidencia')),
            ],
            options={
                'verbose_name': 'Imagen de Incidencia',
                'verbose_name_plural': 'Imágenes de Incidencias',
            },
        ),
    ]
