# Generated by Django 5.2.4 on 2025-10-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenIncidencia',
        ),
    ]
